"""replace MedicineId with medicine_name

Revision ID: 40eb9b751395
Revises: 
Create Date: 2026-07-19 18:48:38.449193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40eb9b751395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_items', sa.Column('medicine_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('prescription_items_MedicineId_fkey'), 'prescription_items', type_='foreignkey')
    op.drop_column('prescription_items', 'MedicineId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_items', sa.Column('MedicineId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('prescription_items_MedicineId_fkey'), 'prescription_items', 'medicines', ['MedicineId'], ['MedicineId'])
    op.drop_column('prescription_items', 'medicine_name')
    # ### end Alembic commands ###
