"""add billing invoices ward bed tables, prescription medicine_name

Revision ID: 51d2581f0e3d
Revises: 40eb9b751395
Create Date: 2026-07-23 18:32:10.119497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d2581f0e3d'
down_revision: Union[str, Sequence[str], None] = '40eb9b751395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('WardId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('daily_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('WardId')
    )
    op.create_table('beds',
    sa.Column('BedId', sa.Integer(), nullable=False),
    sa.Column('WardId', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['WardId'], ['wards.WardId'], ),
    sa.PrimaryKeyConstraint('BedId')
    )
    op.create_table('ward_assignments',
    sa.Column('WardAssignmentId', sa.Integer(), nullable=False),
    sa.Column('PatientId', sa.Integer(), nullable=False),
    sa.Column('BedId', sa.Integer(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(), nullable=True),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['BedId'], ['beds.BedId'], ),
    sa.ForeignKeyConstraint(['PatientId'], ['patients.PatientId'], ),
    sa.PrimaryKeyConstraint('WardAssignmentId')
    )
    op.create_table('invoices',
    sa.Column('InvoiceId', sa.Integer(), nullable=False),
    sa.Column('PatientId', sa.Integer(), nullable=False),
    sa.Column('AppointmentId', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'partial', 'paid', 'cancelled', name='invoicestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('insurance_provider', sa.String(), nullable=True),
    sa.Column('billing_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['AppointmentId'], ['appointments.AppointmentId'], ),
    sa.ForeignKeyConstraint(['PatientId'], ['patients.PatientId'], ),
    sa.PrimaryKeyConstraint('InvoiceId')
    )
    op.create_table('invoice_items',
    sa.Column('InvoiceItemId', sa.Integer(), nullable=False),
    sa.Column('InvoiceId', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('appointment', 'test', 'ward', 'bed', name='invoiceitemtype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['InvoiceId'], ['invoices.InvoiceId'], ),
    sa.PrimaryKeyConstraint('InvoiceItemId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    op.drop_table('ward_assignments')
    op.drop_table('beds')
    op.drop_table('wards')
    # ### end Alembic commands ###
