"""add billing invoices ward bed tables, prescription medicine_na

Revision ID: b58c673aa60b
Revises: 51d2581f0e3d
Create Date: 2026-07-23 19:49:41.244528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58c673aa60b'
down_revision: Union[str, Sequence[str], None] = '51d2581f0e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
