"""add billing invoices ward bed tables, prescription medicinea

Revision ID: ef86cc7cc949
Revises: b58c673aa60b
Create Date: 2026-07-23 19:58:44.278936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef86cc7cc949'
down_revision: Union[str, Sequence[str], None] = 'b58c673aa60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
