from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from sqlalchemy import text
from app.database import get_db

router = APIRouter(
    prefix="/api/reports",
    tags=["Reports"]
)

@router.get("/revenue-by-ward")
def get_revenue_by_ward(db: Session = Depends(get_db)):
    """
    Raw SQL: Calculates total revenue generated by patients assigned to each ward in the last 30 days.
    Demonstrates: 4-table JOIN, COALESCE for NULL handling, INTERVAL date math, SUM aggregate.
    """
    query = text("""
        SELECT 
            w.name AS ward_name, 
            COALESCE(SUM(i.total_amount), 0) AS total_revenue,
            COUNT(i."InvoiceId") AS invoice_count
        FROM wards w
        LEFT JOIN beds b ON w."WardId" = b."WardId"
        LEFT JOIN ward_assignments wa ON b."BedId" = wa."BedId"
        LEFT JOIN invoices i ON wa."PatientId" = i."PatientId" 
            AND i.created_at >= CURRENT_DATE - INTERVAL '30 days'
        GROUP BY w.name
        ORDER BY total_revenue DESC;
    """)
    
    result = db.execute(query).fetchall()
    
    return [
        {
            "ward_name": row.ward_name,
            "total_revenue": float(row.total_revenue),
            "invoice_count": row.invoice_count
        } for row in result
    ]


@router.get("/doctor-appointment-load")
def get_doctor_appointment_load(db: Session = Depends(get_db)):
    """
    Raw SQL: Calculates how many appointments each doctor has handled.
    Demonstrates: JOIN across user and doctor profiles, COUNT aggregate, GROUP BY.
    """
    query = text("""
        SELECT 
            u."FullName" AS doctor_name,
            d.specialty,
            COUNT(a."AppointmentId") AS total_appointments
        FROM doctors d
        JOIN users u ON d."UserId" = u."UserId"
        LEFT JOIN appointments a ON d."DoctorId" = a."DoctorId"
        GROUP BY u."FullName", d.specialty
        ORDER BY total_appointments DESC;
    """)
    
    result = db.execute(query).fetchall()
    
    return [
        {
            "doctor_name": row.doctor_name,
            "specialty": row.specialty,
            "total_appointments": row.total_appointments
        } for row in result
    ]


@router.get("/revenue-by-service-type")
def get_revenue_by_service_type(db: Session = Depends(get_db)):
    """
    Raw SQL: Breaks down total revenue by service type (Appointment, Ward, Bed, Test).
    Demonstrates: JOIN between invoices and invoice items, SUM aggregate.
    """
    query = text("""
        SELECT 
            ii.item_type,
            SUM(ii.subtotal) AS total_revenue,
            COUNT(ii."InvoiceItemId") AS total_items_billed
        FROM invoice_items ii
        JOIN invoices i ON ii."InvoiceId" = i."InvoiceId"
        GROUP BY ii.item_type
        ORDER BY total_revenue DESC;
    """)
    
    result = db.execute(query).fetchall()
    
    return [
        {
            "item_type": row.item_type,
            "total_revenue": float(row.total_revenue),
            "total_items_billed": row.total_items_billed
        } for row in result
    ]